version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: stockpanzee-db
    restart: unless-stopped
    env_file:
      - ./_db/.env
    volumes:
      - stockpanzee_pgdata:/var/lib/postgresql/data
      - ./_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: stockpanzee-api
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads 
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: stockpanzee-web
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:

volumes:
  stockpanzee_pgdata:
