# /docker-compose.yml
version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stockpw
      POSTGRES_DB: stockdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: stock-api
    command: npm run dev
    volumes:
      - ./backend:/app # 로컬 백엔드 코드를 컨테이너에 마운트
      - /app/node_modules # 컨테이너의 node_modules 사용
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: stock-web
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app # 로컬 프론트엔드 코드를 컨테이너에 마운트
      - /app/node_modules # 컨테이너의 node_modules 사용
    env_file: ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # 파일 변경 감지를 polling 방식으로 진행
      - CHOKIDAR_INTERVAL=100 # (선택) polling 간격(ms)를 낮춰 더 빠른 반영을 유도
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
